nome = input("Digite seu nome:")
cpf = input("Digite seu CPF:")
endereco = input("Digite seu endereco:")
idade = input("Digite sua idade")
print('Nome:', nome, 'CPF:', cpf, 'Endereco:', endereco, 'Idade:', idade)